### ISSUE TITLE
Pull ambassador-agent image from private registry

### ISSUE THREAD

**Issue by selenaanguyenn** [datawire/ambassador-agent#104]
## Summary

Some users may have private clusters and want to pull any Docker images needed from an internal or private registry instead of the public `datawire` one. In this case, they'll want an option to pull the `ambassador-agent` image from their own registry as well.

## Feature

Ability to set the registry from where the `ambassador-agent` image is pulled. In addition to this, it would also be helpful if they could set the name and tag of their image to use. For example, something similar to these values from the traffic manager:

```
image:
  registry: {INTERNAL_REGISTRY}
  name: tel2
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
```
